WIND_DIRECTION_CODE = {
    "N": "North",
    "NNE": "North-Northeast",
    "NE": "Northeast",
    "ENE": "East-Northeast",
    "E": "East",
    "ESE": "East-Southeast",
    "SE": "Southeast",
    "SSE": "South-Southeast",
    "SSW": "South-Southwest",
    "SW": "Southwest",
    "WSW": "West-Southwest",
    "W": "West",
    "WNW": "West-Northwest",
    "NW": "Northwest",
    "NNW": "North-Northwest",
    "VARIABLE": "Fluctuate"
}

WEATHER_CODE = {
    "0": "Clear Skies",
    "1": "Partly Cloudy",
    "2": "Partly Cloudy",
    "3": "Mostly Cloudy",
    "4": "Overcast",
    "5": "Haze",
    "10": "Smoke",
    "45": "Fog",
    "60": "Light Rain",
    "61": "Rain",
    "63": "Heavy Rain",
    "80": "Isolated Shower",
    "95": "Severe Thunderstorm",
    "97": "Severe Thunderstorm",
    "100": "Clear Skies",
    "101": "Partly Cloudy",
    "102": "Partly Cloudy",
    "103": "Mostly Cloudy",
    "104": "Overcast"
}

PROVINCES = {
    "aceh": "DigitalForecast-Aceh.xml", 
    "bali": "DigitalForecast-Bali.xml", 
    "bangka_belitung": "DigitalForecast-BangkaBelitung.xml", 
    "banten": "DigitalForecast-Banten.xml", 
    "bengkulu": "DigitalForecast-Bengkulu.xml", 
    "dki_yogyakarta": "DigitalForecast-DIYogyakarta.xml", 
    "dki_jakarta": "DigitalForecast-DKIJakarta.xml", 
    "gorontalo": "DigitalForecast-Gorontalo.xml", 
    "jambi": "DigitalForecast-Jambi.xml", 
    "jawa_barat": "DigitalForecast-JawaBarat.xml", 
    "jawa_tengah": "DigitalForecast-JawaTengah.xml", 
    "jawa_Timur": "DigitalForecast-JawaTimur.xml", 
    "kalimantan_barat": "DigitalForecast-KalimantanBarat.xml", 
    "kalimantan_selatan": "DigitalForecast-KalimantanSelatan.xml", 
    "kalimantan_tengah": "DigitalForecast-KalimantanTengah.xml", 
    "kalimantan_timur": "DigitalForecast-KalimantanTimur.xml", 
    "kalimantan_utara": "DigitalForecast-KalimantanUtara.xml", 
    "kepulauan_riau": "DigitalForecast-KepulauanRiau.xml", 
    "lampung": "DigitalForecast-Lampung.xml", 
    "maluku": "DigitalForecast-Maluku.xml", 
    "maluku_utara": "DigitalForecast-MalukuUtara.xml", 
    "nusa_tenggara_barat": "DigitalForecast-NusaTenggaraBarat.xml", 
    "nusa_tenggara_timur": "DigitalForecast-NusaTenggaraTimur.xml", 
    "papua": "DigitalForecast-Papua.xml", 
    "papua_barat": "DigitalForecast-PapuaBarat.xml", 
    "riau": "DigitalForecast-Riau.xml", 
    "sulawesi_barat": "DigitalForecast-SulawesiBarat.xml", 
    "sulawesi_selatan": "DigitalForecast-SulawesiSelatan.xml", 
    "sulawesi_sengah": "DigitalForecast-SulawesiTengah.xml", 
    "sulawesi_tenggara": "DigitalForecast-SulawesiTenggara.xml", 
    "sulawesi_utara": "DigitalForecast-SulawesiUtara.xml", 
    "sumatera_barat": "DigitalForecast-SumateraBarat.xml", 
    "sumatera_selatan": "DigitalForecast-SumateraSelatan.xml", 
    "sumatera_utara": "DigitalForecast-SumateraUtara.xml", 
    "indonesia": "DigitalForecast-Indonesia.xml"
}